### ISSUE TITLE
Start up maple seed 2 and this error appears and it crash and shut down.

### ISSUE THREAD

**Issue by unicklive** [Tsume/Maple-Tree#115]
Below is the error i get from every time i start maple seed 2.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.<FindAll>d__13.MoveNext()
   at LiteDB.CollectionService.Drop(CollectionPage col)
   at LiteDB.LiteEngine.<>c__DisplayClass45_0.<DropCollection>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at MapleLib.Databases.WiiuTitleDatabase.<InitDatabase>d__14.MoveNext() in E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Tsume** [comment]
Browse to the following directory and delete mapleseed.db

C:\Users\user\AppData\Roaming\MapleTree

**Comment by unicklive** [comment]
Thx tsume, that worked.
