### ISSUE TITLE
[Mapleseed 1.1.0.53] Crashes on initial launch, and error on every launch

### ISSUE THREAD

**Issue by ortonomy** [Tsume/Maple-Tree#118]
# first launch

here's the error:
![capture](https://user-images.githubusercontent.com/6688676/30773584-22bb655a-a0a6-11e7-87eb-cd40d1e4d75e.PNG)

and error log
````
System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleLib.Databases.GraphicPackDatabase.<InitDatabase>d__15.MoveNext() in E:\Projects\MapleTree\MapleLib\Databases\GraphicPackDatabase.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
````

# launches after that

![capture2](https://user-images.githubusercontent.com/6688676/30773598-7479b1ee-a0a6-11e7-84c8-8552c82f633b.PNG)

Error log:
````
System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleLib.Databases.GraphicPackDatabase.<InitDatabase>d__15.MoveNext() in E:\Projects\MapleTree\MapleLib\Databases\GraphicPackDatabase.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
````

and app log:

````
GraphicPacks Init() failed too many times, cancelling...

Could not find file 'C:\Users\GeLiGeLu\AppData\Roaming\MapleTree\graphicPacks'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at MapleLib.Databases.GraphicPackDatabase.<Create>d__17.MoveNext() in E:\Projects\MapleTree\MapleLib\Databases\GraphicPackDatabase.cs:line 100
````

**Comment by Tsume** [comment]
You also get the same issue with 2.1.1.15 hotfix? (https://github.com/Tsume/Maple-Tree/releases/tag/v2.1.1.15-hf1)

**Comment by ortonomy** [comment]
@Tsume -- I haven't tried. I actually think the usability of v1 is better... :blush: I can try the 2.1.1.15 hotfix...

I did test it earlier, and it had a few crashes: when quitting, and when selecting 'dynamic theme'.

**Comment by Tsume** [comment]
Try this version. See if you still get the same error, if so post another screenshot of it. The code is different so it'll be easier to find out where the problem is with the error log.

[MapleSeed_1.1.1.15.zip](https://github.com/Tsume/Maple-Tree/files/1326681/MapleSeed_1.1.1.15.zip)

**Comment by ortonomy** [comment]
It worked! No more errors!

Still has the graphics pack issue though:
![capture3](https://user-images.githubusercontent.com/6688676/30779943-b505c82a-a131-11e7-97ef-7d9e51abd393.PNG)

**Comment by Tsume** [comment]
Did it generate a new error log? I can't recall if it should or not. I suspect it may be due to the download failing.

**Comment by Tsume** [comment]
Oh, that being said. Graphic Packs don't work for V1. It hasn't been implemented into the UI. It's only available for V2 at the moment.

**Comment by Tsume** [comment]
I also believe I've fixed the graphic packs issue. There was a problem with the url detection method that sometimes caused a false "can not be found" error when the url actually still existed. A new update(possibly today), will include that fix.

**Comment by ortonomy** [comment]
@Tsume -- so have you released a version with the graphics pack issue?
