### ISSUE TITLE
error.log Pls Help

### ISSUE THREAD

**Issue by SuperCat2011** [Tsume/Maple-Tree#128]
Yes i have the newest version of mapleseed and newest version of cemu 

---------------------------

---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at MapleLib.Database.<>c__DisplayClass30_0.<FindTitle>b__0(Title x) in E:\projects\MapleTree\MapleLib\Database.cs:line 97

   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at MapleLib.Database.FindTitle(String id) in E:\projects\MapleTree\MapleLib\Database.cs:line 97

   at MapleLib.Database.<>c__DisplayClass31_0.<FindTitleAsync>b__0() in E:\projects\MapleTree\MapleLib\Database.cs:line 107

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at MapleLib.Database.<FindTitleAsync>d__31.MoveNext() in E:\projects\MapleTree\MapleLib\Database.cs:line 107

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at MapleLib.Databases.WiiuTitleDatabase.<LoadLibrary>d__8.MoveNext() in E:\projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:line 78

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at MapleLib.Databases.WiiuTitleDatabase.<Load>d__9.MoveNext() in E:\projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:line 92

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at MapleCake.App.Main()
---------------------------
OK   
---------------------------

**Comment by Tsume** [comment]
Try using 2.1.1.17, the version you’re using doesn’t have any code on the lines in the error log.

**Comment by Azazel25** [comment]
I've got exactly the same issue with the 2.1.1.17

**Comment by Tsume** [comment]
Try using the most recent build 2.1.1.17b. The code's changed a bit and so the lines don't match up anymore. Post the error log here when it generates.
