### ISSUE TITLE
Application doesn't open. 

### ISSUE THREAD

**Issue by robdood** [Tsume/Maple-Tree#67]
Was using 2.1.1.13 prior to this, in a different folder location. 

Drop the mapletree2.exe into Cemu 1.8.0 folder, run it.  Nothing happens; it appears in task manager for a short while then disappears.  Saw this in the closed issues but there was no mention in the threads on how to rectify, so not sure if there's anything I can do about it or not!!

Error log:
`System.ArgumentNullException: Value cannot be null.
Parameter name: format
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MapleLib.Settings.Application_ThreadException(Object sender, ThreadExceptionEventArgs e) in E:\Projects\MapleTree\MapleLib\Settings.cs:line 164
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MapleSeed.Program.Main()`

**Comment by Tsume** [comment]
Use 2.1.1.14

**Comment by robdood** [comment]
This fault was with 2.1.1.14.

I had been using 2.1.1.13 before without issue.

**Comment by kilyan82** [comment]
any overlay, temp monitor active? this software don't like them

**Comment by robdood** [comment]
Oh snap, disabling Rivatuner did it 👍
