### ISSUE TITLE
Crashes on startup using current release

### ISSUE THREAD

**Issue by IamCarbonMan** [Tsume/Maple-Tree#91]
Downloaded current release, on first startup I get the following error:

```
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'MapleCake.ViewModels.MainWindowViewModel' that matches the specified binding constraints threw an exception. ---> System.TypeInitializationException: The type initializer for 'MapleLib.Database' threw an exception. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Griffin\AppData\Roaming\MapleTree\mapleseed.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at MapleLib.Common.Helper.FileOpenStream(String path) in E:\Projects\MapleTree\MapleLib\Common\Helper.cs:line 67
   at MapleLib.Database..cctor() in E:\Projects\MapleTree\MapleLib\Database.cs:line 28
   --- End of inner exception stack trace ---
   at MapleLib.Database.RegisterEvent(EventHandler`1 onEvent)
   at MapleCake.ViewModels.MainWindowViewModel.RegisterEvents()
   at MapleCake.ViewModels.MainWindowViewModel.Init()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MapleCake.App.Main()
```

When running the .Net 4.5.2 installer from MS website it says that .Net 4.5.2 is already installed.

**Comment by Tsume** [comment]
The process cannot access the file 'C:\Users\Griffin\AppData\Roaming\MapleTree\mapleseed.db' because it is being used by another process.

Make sure nothing else is accessing this file. That appears to be why it fails to run.

**Comment by OnlyNeedJuan** [comment]
From what I can tell, Mapleseed doesn't actually properly close, and ends up just being active, which means that it will see itself. Try opening task manager, closing Mapleseed2.exe, and relaunching the program.

**Comment by Tsume** [comment]
I'm starting to see that as a bit of a trend. I haven't been able to replicate it on my system. But if you don't mind, could you send me a generated dxdiag.txt from the PC it happens on? As well as a little details on the types of programs you're running that may interfere/scan other processes?

Dxdiag can be generated by going to Run(WinKey + R) and typing in dxdiag. Click the Save All button.

**Comment by Tsume** [comment]
Either upload it here, or someone else or a pastebin. Avoid pasting it directly, as it's extremely long.

**Comment by IamCarbonMan** [comment]
I'll paste one here in a sec. As for programs that might interfer with
MapleSeed, when I got this error it was the only program running.
